name: Build and Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    env:
      AWS_REGION: ap-south-1
      CLUSTER_NAME: sample-eks-cluster

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify EKS has active nodes
      run: |
        kubectl get nodes
