name: Build and Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    env:
      AWS_REGION: ap-south-1
      CLUSTER_NAME: sample-eks-cluster

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Configure kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name $CLUSTER_NAME

      - name: Verify cluster access
        run: kubectl get nodes
